version: "3.7"

services:

  server:
    restart: on-failure
    build: .
    image: cloudstorage
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=mysql
      - DATABASE_NAME=cloud
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cloud
      - FILE_STORAGE_DIR=/tmp/CLOUD
    volumes:
        - "D:/Programming/CLOUD:/tmp/CLOUD"
    container_name: server

  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=cloud

    ports:
      - "3306:3306"
    container_name: db